In [2]:
import numpy as np

In [3]:
# Creating Arrays

In [20]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
# Array Attributes
arr = np.array([[1,2,3],
                [4,5,6]])

In [41]:
arr.shape

(2, 3)

In [40]:
arr.ndim

2

In [39]:
arr.size

6

In [37]:
arr.dtype

dtype('int64')

In [42]:
# Indexing and Slicing

In [43]:
arr[0]

array([1, 2, 3])

In [44]:
arr[:,1]

array([2, 5])

In [46]:
arr[1,2]

np.int64(6)

In [47]:
# Reshaping Arrays

In [48]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [49]:
arr.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])