In [2]:
import numpy as np

In [ ]:
# Vectorized Operations

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [4]:
a + b

array([5, 7, 9])

In [5]:
a - b

array([-3, -3, -3])

In [6]:
a * b

array([ 4, 10, 18])

In [7]:
a / b

array([0.25, 0.4 , 0.5 ])

In [8]:
a ** b

array([  1,  32, 729])

In [9]:
# Mathematical Functions

In [19]:
arr = np.random.randint(0, 10, size=(2,3))
arr

array([[2, 5, 7],
       [7, 6, 9]], dtype=int32)

In [20]:
arr.mean()

np.float64(6.0)

In [23]:
np.median(arr)

np.float64(6.5)

In [27]:
np.std(arr)

np.float64(2.160246899469287)

In [28]:
np.var(arr)

np.float64(4.666666666666667)

In [30]:
arr.sum()

np.int64(36)

In [31]:
arr.min()

np.int32(2)

In [32]:
arr.max()

np.int32(9)

In [33]:
# Broadcasting

In [34]:
a = np.array([1,2,3,4])

In [35]:
a + 10

array([11, 12, 13, 14])

In [39]:
# Axis Operations

In [43]:
arr = np.array([[1,2,3], 
                [4,5,6]])

In [44]:
np.sum(arr, axis = 0)

array([5, 7, 9])

In [45]:
np.sum(arr, axis=1)

array([ 6, 15])

In [46]:
# Random Numbers

In [51]:
np.random.rand(3)

array([0.91235689, 0.23332305, 0.26786335])

In [50]:
np.random.randint(0,10, size=(4,4))

array([[1, 1, 3, 0],
       [1, 8, 9, 5],
       [8, 2, 2, 0],
       [6, 6, 3, 2]], dtype=int32)

In [53]:
np.random.randn(5)

array([-0.35368019,  1.80984573,  0.64006283,  0.4321689 , -0.262806  ])