In [3]:
import numpy as np

In [4]:
# Matrix Operations

In [7]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[1,2],
              [3,4]])

In [8]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

In [9]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [10]:
# Linear Algebra Basics

In [11]:
np.linalg.inv(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [ ]:
# Simulating ML Data

In [19]:
X = np.random.rand(100,3)
y = X[:,0]*2 + X[:,1]*3 + np.random.randn(100)
y

array([ 2.79203072,  5.26420477,  5.73755589,  2.82621279,  4.92927974,
        0.29866152,  1.58904318, -0.70691032,  1.29169494,  2.51978829,
        4.11796331,  1.4002544 ,  3.00683694,  0.80367271,  1.08654842,
        6.68346924,  2.56496254,  1.28222635,  4.66192072,  0.6344295 ,
        2.40580426,  1.17157062,  2.07021878,  0.07754932,  2.00608283,
        3.88226672,  2.57918193,  4.07874448,  4.1389023 ,  4.5167225 ,
        5.20518877,  2.26546401,  2.38476839,  2.26543521,  3.01363543,
        1.21962023,  2.74377346,  3.77639764,  2.55813974,  2.73639552,
        4.6147163 ,  0.6839682 ,  4.42562586,  3.60782785,  1.6802576 ,
        2.23597512,  2.75775016,  4.53082175,  5.40258197,  2.09876705,
        1.13455256,  0.46753035,  1.6811944 ,  4.48708434,  1.86493203,
        1.84883173,  1.44585449,  1.48840312,  1.96733109,  1.6812515 ,
        4.5863102 ,  1.93005517,  1.28468907,  5.29462969,  1.35908912,
        1.49368583,  0.83885537,  2.85545443,  3.71481788,  3.14