In [1]:
import numpy as np

In [2]:
# Matrix Operations

In [3]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[1,2],
              [3,4]])

In [4]:
np.dot(a,b)

array([[ 7, 10],
       [15, 22]])

In [5]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [6]:
# Linear Algebra Basics

In [7]:
np.linalg.inv(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [9]:
# Simulating ML Data

In [10]:
X = np.random.rand(100,3)
y = X[:,0]*2 + X[:,1]*3 + np.random.randn(100)
y

array([ 1.02598862e+00,  4.11582370e+00,  4.42630193e-01,  6.05455303e+00,
        1.70573153e+00,  2.29126077e+00,  2.10149090e+00,  2.79502921e+00,
        2.44420285e+00,  1.76022171e+00,  4.24206327e+00,  2.89026496e+00,
        5.35246889e+00,  1.72046120e+00,  2.73654108e+00,  2.91479219e+00,
        4.12989157e+00,  6.70193349e-01,  9.15093156e-01,  5.70534009e+00,
        3.40327503e+00,  1.36846799e+00,  3.27823601e+00,  3.10408230e+00,
        2.05334742e+00,  1.77357288e-01,  3.43173476e+00,  1.40349342e+00,
        1.02833129e+00,  5.48592677e+00,  2.56021303e+00,  3.28344449e+00,
        2.21585626e+00,  1.85369437e+00,  3.87626598e+00,  2.71759796e+00,
       -6.53150239e-02,  3.96508879e+00,  7.18079951e-01,  4.73252632e+00,
        3.75724256e+00,  3.27241302e+00,  4.25693267e+00,  1.39125081e+00,
        2.57251787e+00,  2.00506060e-02,  1.74667760e+00,  1.96998107e+00,
        2.51067327e+00,  3.42302457e+00,  2.55474926e+00,  7.44471197e-01,
        2.45294970e+00,  